### ISSUE TITLE
Needed tools

### ISSUE THREAD

**Issue by Dviros** [PoSHMagiC0de/BBTPS#1]
Hey dude, thanks a lot for your payload.
It's important to add the following tools as a requirement (took me some time to understand):
https://forums.hak5.org/index.php?/topic/40971-info-tools/

Thanks,
Dvir

**Comment by PoSHMagiC0de** [comment]
@Dviros 
Thanks man.
I did include in the readme that the impacket tools were required for the smbserver.py and it links to Seb's Hak5 post.  I don't think I can host the package myself since it isn't my project.  If nothing says I can't then I could with the instructions to install it.
